import time_utils as tu
import ru_local as ru


FUEL_PRICES = {
    'АИ-92': 63.04,
    'АИ-95': 67.32,
    'АИ-98': 83.25,
    'АИ-100': 89.10
}

def create_fuel_statistics() -> dict:
    """
    Creates an empty dictionary to track daily fuel sales for each fuel type.
    
    Returns:
        dict: A dictionary with fuel types as keys and 0 as initial sold amount.
    """
    return {fuel: 0 for fuel in FUEL_PRICES.keys()}


def calculate_revenue(car: dict) -> float:
    """
    Calculates revenue for a single car based on fuel type and amount.
    
    Args:
        car (dict): Dictionary with car info (fuel type and amount).
    
    Returns:
        float: Revenue generated by the car.
    """
    return FUEL_PRICES[car[ru.car_keys['oil_type']]] * car[ru.car_keys['fuel_amount']]


def update_fuel_statistics(fuel_stats: dict, car: dict) -> None:
    """
    Updates total fuel sold after serving a car.
    
    Args:
        fuel_stats (dict): Dictionary tracking fuel sold per type.
        car (dict): Dictionary with car info.
    """
    fuel_stats[car[ru.car_keys['oil_type']]] += car[ru.car_keys['fuel_amount']]


def print_station_status(stations: list[dict], queues: dict) -> None:
    """
    Prints current status of fuel pumps with queue visualization.
    Each car in queue is represented by '*'.
    
    Args:
        stations (list[dict]): List of stations.
        queues (dict): Current queues per station.
    """
    for station in stations:
        num = station[ru.car_keys['num']]
        capacity = station[ru.station_labels['max_queue']]
        oil_types = " ".join(station[ru.station_labels['fuel_types']])
        line = (f"{ru.station_labels['station']} №{num} "
                f"{ru.station_labels['max_queue']}: {capacity} "
                f"{ru.station_labels['fuel_types']}: {oil_types} ->")
        queue = queues[num]
        line += "*" * len(queue)
        print(line)
    print()


def print_daily_statistics(fuel_stats: dict, total_revenue: float, lost_revenue: float) -> None:
    """
    Prints daily summary: fuel sold, total revenue, and lost revenue.
    
    Args:
        fuel_stats (dict): Sold liters per fuel type.
        total_revenue (float): Total revenue.
        lost_revenue (float): Lost revenue due to unserved cars.
    """
    print(f"\n===== {ru.daily_stats['title']} =====")
    print(f"\n{ru.daily_stats['sold']}:\n")
    for fuel, amount in fuel_stats.items():
        print(f"{fuel}: {amount} {ru.daily_stats['liters']}")
    print(f"\n{ru.daily_stats['total_revenue']}: {total_revenue:.2f} {ru.daily_stats['currency']}")
    print(f"{ru.daily_stats['lost_revenue']}: {lost_revenue:.2f} {ru.daily_stats['currency']}")
