# ERRORS
FOUND_INCORRECT_DATE = 'Обнаружена строка с некорректной датой'
FOUND_INCORRECT_SUM = 'Обнаружена строка с некорректной суммой'
LOST_INCORRECT_DATA_EL = 'Пропущен элемент с некорректной датой'
DIVERSED_OR_UNKNOWN = 'Файл содержит смешанные или неизвестные типы данных!'
NO_DATA_FOR_ANALYSIS = 'Нет данных для анализа'
NO_DATA_FOR_BUDGET = 'Нет данных для создания бюджета'
FILE_EMPTY_OR_INVALID = 'Файл пуст или не содержит валидных данных'
FILE_NOT_FOUND = 'Файл не найден'
ANALYSIS_ERROR = 'Ошибка анализа: '

# CATEGORIES
FOOD = 'Еда'
TRANSPORT = 'Транспорт'
AMUSEMENT = 'Развлечения'
HEALTH = 'Здоровье'
HOME = 'Дом'
SPORT = 'Спорт'
OTHER = 'Другое'

# SUBCATEGORIES
GORODOK = 'городок'
X5 = 'пятёрочка'
YARCHE = 'ярче'
SAMOKAT = 'самокат'
PRODUCTS = 'продукты'
DINNER = 'обед'
SUSHI = 'суши'
BUS = 'автобус'
TAXI = 'такси'
PETROL = 'бензин'
SCOOTER = 'самокат'
RESTAURANT = 'ресторан'
THEATRE = 'театр'
CINEMA = 'кино'
CONCERT = 'концерт'
TOUR = 'тур'
RECREATION = 'отдых'
DOCTOR = 'врач'
DRUGS = 'лекарства'
HOSPITAL = 'больница'
EYES = 'глаза'
DENTIST = 'стоматолог'
PHARMACY = 'аптека'
UTILITIES = 'коммунальные услуги'
RENT = 'аренда квартиры'
FURNITURE = 'мебель'
FITNESS = 'фитнес'
YOGA = 'йога'
POOL= 'бассейн'
GYM = 'зал'
TENNIS = 'теннис'
MASSAGE = 'массаж'

# FINANCIAL STATISTICS
INCOME = 'Доход'
INCOMES = 'Доходы'
EXPENSE = 'Расход'
EXPENSES = 'Расходы'
BALANCE = 'Баланс'
AMOUNT = 'Количество операций'
COSTS = 'Затраты'
COSTS_PART = 'Доля в общих расходах'

# BUDGET PLANNING
SAVINGS = 'накопления'
EMERGENCY = 'непредвиденные'
TOTAL_PLANNED_EXPENSES = 'total_planned_expenses'
SAVINGS_PERCENTAGE = 'savings_percentage'
EMERGENCY_PERCENTAGE = 'emergency_percentage'
CREATION_DATE = 'creation_date'
WITHIN_BUDGET = 'в рамках бюджета'
EXCEEDED = 'превышение'
NO_DATA = 'нет данных'
BUDGET_AMOUNT = 'budget_amount'
ACTUAL_AMOUNT = 'actual_amount'
DIFFERENCE = 'difference'
PERCENTAGE = 'percentage'
STATUS = 'status'
CATEGORY_COMPARISON = 'category_comparison'
SUMMARY = 'summary'
TOTAL_BUDGET = 'total_budget'
TOTAL_ACTUAL = 'total_actual'
TOTAL_DIFFERENCE = 'total_difference'
OVERALL_STATUS = 'overall_status'
EXCEEDED_CATEGORIES = 'exceeded_categories'
WITHIN_BUDGET_CATEGORIES = 'within_budget_categories'

# MONTHS
JANUARY = 'Январь'
FEBUARY = 'Февраль'
MARCH = 'Март'
APRIL = 'Апрель'
MAY = 'Май'
JUNE = 'Июнь'
JULY = 'Июль'
AUGUST = 'Август'
SEPTEMBER = 'Сентябрь'
OCTOBER = 'Октябрь'
NOVEMBER = 'Ноябрь'
DECEMBER = 'Декабрь'

# REPORT
FINANCIAL_REPORT = '===ФИНАНСОВЫЙ ОТЧЁТ===\n'
MAIN_RATIOS = 'ОСНОВНЫЕ ПОКАЗАТЕЛИ:'
MONTH_STATS = '\n===СТАТИСТИКА ПО МЕСЯЦАМ==='
CATEGORY_STATS = '\nРАСХОДЫ ПО КАТЕГОРИЯМ'
BUDGET_RECCOMENDATIONS = '\nРЕКОМЕНДАЦИИ ПО БЮДЖЕТУ'

# BUDGET MESSAGES
BIGGEST_SPENDING = 'Самые большие траты в категории'
SEASONALITY_DETECTED = 'Наблюдается сезонность в категории'
PEAK_MONTH = 'Месяц с максимальными тратами на категорию'
RECOMMENDED_SAVINGS = 'Рекомендуется откладывать'
PERCENT_OF_ALL_EXPENSES = 'от всех расходов'
EXCELLENT_BUDGET = 'Отлично! Вы укладываетесь в бюджет'
BUDGET_EXCEEDED = 'Превышение бюджета на'
ATTENTION = 'Внимание'
GOAL = 'Цель'
REDUCE_SPENDING = 'Сократить траты на'
BY_PERCENT = 'на 10%'
RUB = 'руб.'

# ANALYSIS STRUCTURE
HISTORICAL_ANALYSIS = 'historical_analysis'
BUDGET_TEMPLATE = 'budget_template'
COMPARISON_REPORT = 'comparison_report'
AVERAGE_BY_CATEGORY = 'average_by_category'
SEASONAL_PATTERNS = 'seasonal_patterns'
TOP_CATEGORIES = 'top_categories'
RECOMMENDATIONS = 'recommendations'
CURRENT_MONTH_STATS = 'current_month_stats'
METADATA = '_metadata'
ERROR = 'error'
