data_report = 'ОТЧЕТ ОПЕРАЦИИ \'DATA SHIELD\''
financial = 'ФИНАНСОВЫЕ ДАННЫЕ'
secrets = 'СЕКРЕТНЫЕ КЛЮЧИ'
system = 'СИСТЕМНАЯ ИНФОРМАЦИЯ'
encoded = 'РАСШИФРОВАННЫЕ СООБЩЕНИЯ'
threats = 'УГРОЗЫ БЕЗОПАСНОСТИ'
normilized = 'НОРМАЛИЗОВАННЫЕ ДАННЫЕ'
